models/Sermon.php
<?php

namespace app\models;

/**
 * Class Sermon
 * @package app\models
 *
 * @property integer $id
 * @property string $title
 * @property integer $groupId
 * @property array $language
 * @property string $picture
 * @property string $notes
 * @property string $filesJson
 * @property array $files
 * @property array $scriptures
 * @property string $scripturesJson
 * @property string $date
 * @property integer $hits
 * @property string $seriesName
 * @property string $speaker
 * @property string $youtube
 * @property integer hidden
 * @property integer $duration (in seconds)
 * @property boolean $showOnlyDirect
 *
 * @property Group $group
 *
 */

class Sermon extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'sermon';
    }
    public function rules()
    {
        return [
            [['title', 'speaker', 'groupId', 'language'], 'required'],
            [['title',  'filesJson', 'scripturesJson', 'picture', 'notes', 'speaker', 'seriesName', 'youtube'], 'string'],
            [['hits', 'groupId', 'hidden', 'duration', 'showOnlyDirect'], 'integer'],
            [['files', 'scriptures'], 'safe']
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(Group::class, ['id' => 'groupId']);
    }

    public function getFiles()
    {
        $data = json_decode($this->filesJson, true);
        if ($data === false) {
            return [];
        }
        return $data;
    }
    public function setFiles($newValue)
    {
        if (isset($newValue['other'])) {
            $newValue['other'] = array_unique($newValue['other']);
        }
        if (isset($newValue['audio'])) {
            $newValue['audio'] = array_unique($newValue['audio']);
        }
        if (isset($newValue['video'])) {
            $newValue['video'] = array_unique($newValue['video']);
        }
        if (isset($newValue['image'])) {
            $newValue['image'] = array_unique($newValue['image']);
        }
        $this->filesJson = json_encode($newValue);
    }
    public function getScriptures()
    {
        $data = json_decode($this->scripturesJson, true);
        if ($data === false) {
            return [];
        }
        return $data;
    }

    public function setScriptures($response)
    {
        $this->scripturesJson = json_encode($response);
    }

    public function getAlternativeCover()
    {
        if (isset(\Yii::$app->params['covers'])) {
            $path = \Yii::$app->params['covers'];
            return "$path/{$this->group->code}-{$this->language}.jpg";
        }
        return "";
    }
}

controllers/SermonController.php
<?php

namespace app\controllers;

use app\helpers\Feed;
use app\helpers\Scripture;
use app\models\Group;
use app\models\Sermon;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class SermonController extends JsonController
{
    public $enableCsrfValidation = false;

    public function behaviors()
    {
        return [
            [
                'class' => 'yii\filters\ContentNegotiator',
                'only' => ['rss', 'feed'],
                'formats' => [
                    'application/xml' => Response::FORMAT_RAW,
                    'application/rss+xml' => Response::FORMAT_RAW,
                    'text/xml' => Response::FORMAT_RAW,
                    'text/html' => Response::FORMAT_RAW,
                ],
            ],
            [
                'class' => 'yii\filters\ContentNegotiator',
                'only' => ['hit', 'list', 'create', 'add', 'series', 'info', 'languages', 'speakers', 'series-data'],
                'formats' => [
                    'application/json' => Response::FORMAT_JSON,
                    'text/xml' => Response::FORMAT_JSON,
                    'text/html' => Response::FORMAT_JSON,
                ],
            ],
        ];
    }


    public function actionIndex($id)
    {
        $sermon = Sermon::find()->where(['id' => $id])->andWhere(['hidden' => false])->one();
        if ($sermon === null) {
            throw new NotFoundHttpException('The requested sermon does not exist.');
        }
        $this->view->params['feedUrl'] = aurl(['sermon/feed', 'groupCode' => $sermon->group->code, 'language' => ""]);
        $this->view->title = $sermon->title;
        return $this->render('sermon', ['sermon' => $sermon]);
    }

    /**
     * @param $id
     * @return array
     * old url: /sermon/hit/#SermonId UpdateDownloadCounterR GET
     */
    public function actionHit($id)
    {
        $sermon = $this->findModel($id);
        if (empty($sermon->hits)) {
            $sermon->hits = 1;
        } else {
            $sermon->hits++;
        }
        $sermon->save();
        return ['response' => 'ok'];
    }

    /**
     * @return array
     */
    public function actionList()
    {
        $sermons = $this->getQuery();
        return $this->sermonList($sermons);
    }



    /**
     * @return string
     * @throws NotFoundHttpException, \Exception
     */
    public function actionFeed($groupCode = "", $language = "")
    {
        $time = new \DateTime('now');
        $today = $time->format('Y-m-d');

        $sermons = Sermon::find()->joinWith('group')
            ->andWhere(['<>', 'hidden', 1])
            ->andWhere(['<=', 'date', $today])
            ->limit(1000);
        $sermons = $sermons->andWhere(['or', ['<>', 'showOnlyDirect', 1], ['showOnlyDirect' => NULL]]);

        $groupName = "";

        if (!empty($groupCode)) {
            $group = Group::findOne(['code' => $groupCode]);
            if (!$group) {
                throw new NotFoundHttpException("group not found");
            }
            $groupName = $group->name;
            $groupCode = $group->code;
            $sermons = $sermons->andWhere(['group.code' => $groupCode]);
        }
        if (!empty($language)) {
            $language = substr($language, 0, 2);
            $sermons = $sermons->andWhere(['sermon.language' => $language]);
        }
        return Feed::createRssFeed($this, $sermons, $groupName, $groupCode, $language);
    }


    /**
     * @return string
     * @throws NotFoundHttpException, \Exception
     */
    public function actionRss()
    {
        $sermons = $this->getQuery()->limit(1000);
        $sermons = $sermons->andWhere(['or', ['<>', 'showOnlyDirect', 1], ['showOnlyDirect' => NULL]]); //always hide
        $groupName = "";
        $language = "";

        $groupCode = "";
        if (isset($_REQUEST['filter']) && isset($_REQUEST['filter']['groupCode']) && !empty($_REQUEST['filter']['groupCode'])) {
            $group = Group::findOne(['code' => $_REQUEST['filter']['groupCode']]);
            if (!$group) {
                throw new NotFoundHttpException("group not found");
            }
            $groupName = $group->name;
            $groupCode = $group->code;
        }
        if (isset($_REQUEST['filter']) && isset($_REQUEST['filter']['language'])) {
            $language = substr($_REQUEST['filter']['language'], 0, 2);
        }
        return Feed::createRssFeed($this, $sermons, $groupName, $groupCode, $language);
    }

    /**
     * @return ActiveQuery
     * @throws \Exception
     */
    private function getQuery()
    {
        $filter = isset($_REQUEST['filter']) ? $_REQUEST['filter'] : [];
        $sort = isset($_REQUEST['sort']) ? $_REQUEST['sort'] : [];
        $limit = isset($_REQUEST['limit']) ? $_REQUEST['limit'] : 0;
        $offset = isset($_REQUEST['offset']) ? $_REQUEST['offset'] : 0;
        $showDirect = isset($_REQUEST['showDirect']) ? intval($_REQUEST['showDirect']) : 0;

        $time = new \DateTime('now');
        $today = $time->format('Y-m-d');

        $sermons = Sermon::find()->joinWith('group')
            ->andWhere(['<>', 'hidden', 1])
            ->andWhere(['<=', 'date', $today]);
        if($showDirect == 0) {
            $sermons = $sermons->andWhere(['or', ['<>', 'showOnlyDirect', 1], ['showOnlyDirect' => NULL]]);
        }

        if (isset($filter['groupCode']) && !empty($filter['groupCode'])) {
            $sermons = $sermons->andWhere(['group.code' => $filter['groupCode']]);
        }
        if (isset($filter['seriesName']) && !empty($filter['seriesName'])) {
            if(contains(" ", $filter['seriesName'])) {
                $sermons = $sermons->andWhere(['sermon.seriesName' => $filter['seriesName']]);
            } else {
                $sermons = $sermons->andWhere(['like', 'sermon.seriesName', $filter['seriesName']]);
            }
           
        }
        if (isset($filter['title']) && !empty($filter['title'])) {
            $sermons = $sermons->andWhere(['like', 'sermon.title', $filter['title']]);
        }
        if (isset($filter['speaker']) && !empty($filter['speaker'])) {
            $sermons = $sermons->andWhere(['like', 'sermon.speaker', $filter['speaker']]);
        }
        if (isset($filter['id'])) {
            $sermons = $sermons->andWhere(['sermon.id' => $filter['id']]);
        }
        if (isset($filter['language']) && !empty($filter['language'])) {
            $sermons = $sermons->andWhere(['sermon.language' => $filter['language']]);
        }
        if (isset($filter['all'])) {
            $sermons = $sermons->andFilterWhere([
                'or',
                ['like', 'seriesName', $filter['all']],
                ['like', 'title', $filter['all']],
                ['like', 'speaker', $filter['all']]
            ]);
        }
        if ($limit != 0) {
            $sermons = $sermons->limit($limit);
        }

        if ($offset != 0) {
            $sermons = $sermons->offset($offset);
        }

        if (!empty($sort) && is_array($sort)) {
            $s = [];
            foreach ($sort as $key => $order) {
                if ($order === "asc") {
                    $s[$key] = SORT_ASC;
                } else {
                    $s[$key] = SORT_DESC;
                }
            }
            $s['title'] = SORT_ASC;
            $sermons = $sermons->orderBy($s);
        } else {
            $sermons = $sermons->orderBy(['date' => SORT_DESC, 'title' => SORT_ASC]);
        }
        return $sermons;
    }

    /**
     * @param ActiveQuery $query
     * @return array
     */
    private function sermonList($query)
    {
        $ret = [];
        foreach ($query->each() as $sermon) {
            /** @var Sermon $sermon */
            if (empty($sermon->files['image'])) {
                $images = [$sermon->getAlternativeCover()];
            } else {
                $images = $sermon->files['image'];
            }

            $item = [
                'id' => $sermon->id,
                'title' => $sermon->title,
                'audio' => $this->addWebProtocol($sermon->files['audio']),
                'video' => $this->addWebProtocol($sermon->files['video']),
                'other' => $this->addWebProtocol($sermon->files['other']),
                'image' => $this->addWebProtocol($images),
                'speaker' => $sermon->speaker,
                'seriesName' => empty($sermon->seriesName) ? "" : $sermon->seriesName,
                'date' => \Yii::$app->formatter->asDate($sermon->date, 'short'),
                'utcDate' => $sermon->date,
                'realDate' => $sermon->date,
                'language' => $sermon->language,
                'dateLocale' => [
                    'shortMonth' => \Yii::$app->formatter->asDate($sermon->date, 'php:M'),
                    'longMonth' => \Yii::$app->formatter->asDate($sermon->date, 'php:F'),
                ],
                'scripture' => $this->scriptureText($sermon),
                'scriptureData' => $sermon->scriptures,
                'groupCode' => $sermon->group->code,
                'youtube' => $sermon->youtube,
            ];
            $ret[] = $item;
        }
        return [
            'count' => $query->count(),
            'total' => $query->limit(null)->offset(null)->count(),
            'query' => $query->createCommand()->getRawSql(),
            'sermons' => $ret,
        ];
    }
    private function addWebProtocol($files)
    {
        $ret = [];
        foreach ($files as $id => $file) {
            if (startsWith('//', $file)) {
                $ret[] = "https:" . $file;
            } elseif (startsWith('http://', $file)) {
                $ret[] = str_replace("http:", "https:", $file);
            } else {
                $ret[] = $file;
            }
        }
        return $ret;
    }

views/sermon/rss.php
<?php
/** @var \yii\db\ActiveQuery $sermons */
use app\helpers\Feed;
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
$url = aurl(['sermon/feed', 'groupCode' => $groupCode, 'language' => $language]);
?>

<rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:googleplay="http://www.google.com/schemas/play-podcasts/1.0/play-podcasts.xsd">
    <channel>
        <title><?= $title ?></title>
        <atom:link href="<?= str_replace("&", "&amp;", aurl($url)); ?>" rel="self" type="application/rss+xml" />
        <link><?= $link ?></link>
        <description><?= $description ?></description>
        <image>
            <title><?= $title ?></title>
            <url><?= $cover ?></url>
            <link><?= $link ?></link>
        </image>

        <lastBuildDate><?= $lastBuildDate->format(DateTime::RFC2822) ?></lastBuildDate>
        <language><?= $language ?></language>
        <sy:updatePeriod>hourly</sy:updatePeriod>
        <sy:updateFrequency>3</sy:updateFrequency>
        <generator>https://gitlab.com/ecg-berlin/vue-sermons</generator>
        <copyright><?= Yii::$app->params['copyright'] ?></copyright>
        <itunes:subtitle><?= $subtitle ?></itunes:subtitle>
        <itunes:summary>
            <?= $description ?></itunes:summary>
        <itunes:explicit>clean</itunes:explicit>
        <itunes:author><?= Yii::$app->params['channelName'] ?></itunes:author>
        <itunes:owner>
            <itunes:name><?= Yii::$app->params['channelName'] ?></itunes:name>
            <itunes:email><?= Yii::$app->params['channelEMail'] ?></itunes:email>
        </itunes:owner>
        <itunes:category text="Religion &amp; Spirituality">
            <itunes:category text="Christianity" />
        </itunes:category>
     
        <itunes:image href="<?= $cover ?>"></itunes:image>
        <itunes:link rel="image" type="video/jpeg" ><?= $cover ?></itunes:link>

        <googleplay:email><?= Yii::$app->params['channelEMail'] ?></googleplay:email>
        <googleplay:description><?= $description ?></googleplay:description>
        <googleplay:category text="Religion &amp; Spirituality" />
        <googleplay:image href="<?= $cover ?>" />

        <?php foreach ($sermons->each() as $sermon) {
            /** @var \app\models\Sermon $sermon */
            $date = new \DateTime($sermon->date);
            if (!isset($sermon->files["audio"])) {
                continue;
            }
            if (empty($sermon->files["audio"])) {
                continue;
            }

            $mp3 = 'http:' . $sermon->files["audio"][0];
            $mp3 = str_replace(" ", rawurlencode(" "), $mp3);

            $mp3 = str_replace("&", "&amp;", $mp3);
            $mp3 = str_replace("<", "&lt;", $mp3);
            $mp3 = str_replace("\"", "&quot;", $mp3);
            $mp3 = str_replace("'", "&apos;", $mp3);


            $title  = htmlspecialchars($sermon->title, ENT_XML1, 'UTF-8');
            $author = htmlspecialchars($sermon->speaker, ENT_XML1, 'UTF-8');
            $permaLink = aurl(['sermon/index', 'id' => $sermon->id]);
            echo "  <item>\n";
            echo "    <link>" . $permaLink . "</link>\n";
            echo "    <title>$title ($author)</title>\n";
            echo "    <pubDate>{$date->format(DateTime::RFC2822)}</pubDate>\n";
            echo "    <guid isPermaLink='true'>" . $permaLink . "</guid>\n";
            echo "    <itunes:author>{$author}</itunes:author>\n";
            echo "    <itunes:explicit>clean</itunes:explicit>\n";
            echo "    <itunes:episodeType>full</itunes:episodeType>\n";
            $images = $sermon->files['image'];
            if(!empty($images)) {
                $image = Feed::createFeedUrl(array_shift($images));
                echo "    <itunes:image href='$image'/>\n";
            }
            


            if(!empty($sermon->duration) && $sermon->duration > 0) {
                echo "    <itunes:duration>".gmdate("H:i:s", $sermon->duration)."</itunes:duration>\n";
            }
            $desc = "";
            $desc .= "\"$title\" von $author am " . \Yii::$app->formatter->asDate($date->format(DateTime::RFC2822), "medium") . ". \n\r";

            $desc .= "Weitere Infos unter $permaLink\n";

            if (!empty($desc)) {
                echo "    <description>$desc</description>\n";
                echo "    <itunes:summary>$desc</itunes:summary>\n";
            }

            echo "    <enclosure length='1' url='$mp3' type='audio/mpeg'/>\n";
            echo "  </item>";
        } ?>
    </channel>
</rss>

views/sermon/sermon.php
<?php
/** @var \app\models\Sermon $sermon */
?>
<h1><?= $sermon->title?></h1>
<p>Sprecher: <?= $sermon->speaker?></p>
<p>Datum: <?= $sermon->date?></p>
<p>Serie: <?= $sermon->seriesName?></p>
<?php foreach ($sermon->files as $type => $files) {
  if(count($files) != 0) {
    echo "<p>";
    foreach ($files as $file) {
      echo "<a href='$file'>$file</a>";
    }
    echo "</p>";
  }
}?>

<single-sermon :sermon-id='<?= $sermon->id?>'></single-sermon>